[workspace]
members = [
    "type_define/structure",
    "type_define/description_generator",
    "json",
    "langs/rust",
    "langs/go",
    "utils",
    "cli/sf_df",
    "cli/commands",
    "lang_parser"
]
