[package]
name = "lang-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = {version = "0.1.0",path = "../json"}
npc ={ git = "https://github.com/u-kai/npc.git"}